nginx:
  build: .
  dockerfile: /docker/etc/docker/dockerfile_nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./:/etc/nginx/html
  links:
    - php7

php7:
  build: .
  dockerfile: /docker/etc/docker/dockerfile_php_7
  volumes:
    - ./:/var/www/html
    - ./docker/etc/php:/usr/local/etc/php
    - ./:/etc/nginx/html
  links:
    - mysql

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root123


