version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: /docker/etc/docker/dockerfile_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/etc/nginx/html
    depends_on:
      - php7

  php7:
    build:
      context: .
      dockerfile: /docker/etc/docker/dockerfile_php_7
    volumes:
      - ./:/var/www/html
      - ./docker/etc/php:/usr/local/etc/php
      - ./:/etc/nginx/html
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: /docker/etc/docker/dockerfile_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=lumen_api_skell
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=userapp123


